<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__address</name>
   <tag></tag>
   <elementGuidId>06343a03-ad24-47e8-8ef9-f628ec090683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ff5b3ac-7722-4755-973c-a79c9c9c1859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eefafb3-818e-455f-a72a-6ee10b6d0a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>c4b0a129-8e7e-4877-b887-7f9d64f78614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout__input__add</value>
      <webElementGuid>4a017258-a2af-4158-b471-60b588523862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-6&quot;]/div[@class=&quot;checkout__input&quot;]/input[@class=&quot;checkout__input__add&quot;]</value>
      <webElementGuid>66ecd65b-b765-4b25-ac83-fab732dc4630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>3aa25505-5b3e-4e12-8bae-2b40c567e3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/div/div[2]/input</value>
      <webElementGuid>a8e2e5d2-8d3a-45fa-a5b2-4b70e83033cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>95120642-4398-480f-be6c-40e3413f918b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address']</value>
      <webElementGuid>0d61a2fe-db02-4c87-9ded-3ca12d5b6573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
