<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Banners_pcoded-micon</name>
   <tag></tag>
   <elementGuidId>7b9e7244-fd99-47da-a281-e72fc43c9056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li[12]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; About&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f7f8891-032b-4e10-8ce6-707415ca928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pcoded-micon</value>
      <webElementGuid>16d8fb68-3b50-45bf-bcfd-2f4427a620ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/div[@class=&quot;pcoded-main-container&quot;]/div[@class=&quot;pcoded-wrapper&quot;]/nav[@class=&quot;pcoded-navbar&quot;]/div[@class=&quot;nav-list&quot;]/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;pcoded-inner-navbar main-menu&quot;]/ul[@class=&quot;pcoded-item pcoded-left-item&quot;]/li[@class=&quot;pcoded&quot;]/a[@class=&quot;waves-effect waves-dark&quot;]/span[@class=&quot;pcoded-micon&quot;]</value>
      <webElementGuid>78b25f88-8ad0-4441-9f0e-f4e79a4f659c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li[12]/a/span</value>
      <webElementGuid>49a2838f-d61c-48d0-8370-c832f9696a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banners'])[1]/following::span[1]</value>
      <webElementGuid>a1455ed5-1f3e-4a00-a7bb-fefe41955561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[1]/following::span[3]</value>
      <webElementGuid>c3d0cd4a-6dcb-41c1-802a-4eccb6b1f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::span[1]</value>
      <webElementGuid>b2b592a0-521b-4925-a796-a1557fcda37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[3]</value>
      <webElementGuid>1649fa24-e036-4363-935c-139437bbddfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/a/span</value>
      <webElementGuid>623c240e-84b6-479c-bff4-fcada7bbdf04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
