<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Profile_img-radius</name>
   <tag></tag>
   <elementGuidId>306a1f33-ba13-4e6a-baff-e38060690890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/nav/div/div[2]/ul/li/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-radius</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User-Profile-Image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>edd5ed67-a427-4b0e-9ad7-d66e319031f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>upload/avatar/avatar.jpg</value>
      <webElementGuid>f245a76a-fcb5-4a4b-ad1b-e920b7e234f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-radius</value>
      <webElementGuid>605669b0-edad-418d-9ff6-a27f159b43d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User-Profile-Image</value>
      <webElementGuid>190a0bbc-571e-481e-8f7e-51c9df8a5bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/nav[@class=&quot;navbar header-navbar pcoded-header iscollapsed&quot;]/div[@class=&quot;navbar-wrapper&quot;]/div[@class=&quot;navbar-container container-fluid&quot;]/ul[@class=&quot;nav-right&quot;]/li[@class=&quot;user-profile header-notification&quot;]/div[@class=&quot;dropdown-primary dropdown&quot;]/div[@class=&quot;dropdown-toggle&quot;]/img[@class=&quot;img-radius&quot;]</value>
      <webElementGuid>9afedca1-0fe4-4ff6-8e73-38ab8fb3ccb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/nav/div/div[2]/ul/li/div/div/img</value>
      <webElementGuid>a3162905-c768-4382-a9f6-fdf761c9490d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User-Profile-Image']</value>
      <webElementGuid>930a2c83-ab92-4230-8781-dd284d7f54fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>8ac529c4-7a41-428c-9c27-cff95226d6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'upload/avatar/avatar.jpg' and @alt = 'User-Profile-Image']</value>
      <webElementGuid>bde8ab18-0234-40e6-b966-fa985780e893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
