<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lenovo</name>
   <tag></tag>
   <elementGuidId>e95b6eb1-3d45-4313-8c18-2789866fc039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.item-show_item-content > a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Lenovo')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lenovo&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b15afd8b-c03d-46e7-8d5e-5166682059ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/subcategories/2</value>
      <webElementGuid>a00dcd35-7810-44ae-afca-bc244311bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lenovo</value>
      <webElementGuid>1fbb81bd-b6e1-4962-a191-018aeff734e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;hero&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3&quot;]/div[@class=&quot;hero__categories&quot;]/ul[@class=&quot;submenu-list&quot;]/div[@class=&quot;item-show active&quot;]/div[@class=&quot;item-show_item&quot;]/p[@class=&quot;item-show_item-content&quot;]/a[2]</value>
      <webElementGuid>a20abaf6-1593-4f30-8ee0-bde924df2a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lenovo')])[3]</value>
      <webElementGuid>26d56a26-1e12-46cb-9b53-31e1f56a74d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple (MacBook)'])[3]/following::a[1]</value>
      <webElementGuid>c063c09d-9679-451b-8875-9af65e18d330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[3]/following::a[2]</value>
      <webElementGuid>8ca8fb31-0278-4b74-96a5-fe60e9abe242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dell'])[3]/preceding::a[1]</value>
      <webElementGuid>322c4893-bb89-4d93-8199-b13df9c2f173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surface'])[3]/preceding::a[2]</value>
      <webElementGuid>9890443d-b464-4531-a7dc-3bab54245851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/subcategories/2')])[23]</value>
      <webElementGuid>a9794606-186e-45cd-925b-45f5dd8b9b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a[2]</value>
      <webElementGuid>37f3830a-0aff-4d41-88bd-61cff6a7ca23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/subcategories/2' and (text() = 'Lenovo' or . = 'Lenovo')]</value>
      <webElementGuid>e4a4c9df-0bbf-4ff6-9723-479a0e4ac27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
