<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Give Email</name>
   <tag></tag>
   <elementGuidId>1aa21d40-7ff0-4097-a271-e50a03d7b8ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40bfd1e5-f5d1-4d60-a1e5-6c748212bb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>afd2abf1-95fd-4064-874f-a5ad59413982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>10468d92-f556-4a40-bbae-02ed7e1a9daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Give Email</value>
      <webElementGuid>0239813d-8193-498d-abf7-d4b087e79cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;login-container&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;login-button&quot;]</value>
      <webElementGuid>0b7a69c8-3588-474d-9822-97d63c887046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>d25fc849-d46e-4b3d-b2e7-21786af0a218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recover password'])[1]/following::button[1]</value>
      <webElementGuid>6a59ef2d-d3b4-4ec3-bee8-749c52ce4872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to login page'])[1]/preceding::button[1]</value>
      <webElementGuid>cccc8bb0-83e1-4e9b-9428-465349f3db5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address: 12 Chùa Bộc, Đống Đa, Hà Nội'])[1]/preceding::button[1]</value>
      <webElementGuid>293cc2b7-9f4f-4517-9e43-99893007e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Give Email']/parent::*</value>
      <webElementGuid>9759d844-3fa3-41dd-b52c-46b8bfe5a4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>27471d55-4546-47e3-97ee-760bd3b4be5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Give Email' or . = 'Give Email')]</value>
      <webElementGuid>1b33ba0c-de45-46a5-a62d-4765703d85b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
