<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Become a member of TechZone</name>
   <tag></tag>
   <elementGuidId>b90ec353-f290-40b9-87be-89cc808258e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.login-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[3]/following::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c996ad7d-9f0b-4793-b2ec-57370b2a9ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-title</value>
      <webElementGuid>9775a640-bfb4-4a7b-b4cb-305f875e3a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Become a member of TechZone</value>
      <webElementGuid>e4409fbf-0bb3-467e-8a8f-c9b545f525ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/h2[@class=&quot;login-title&quot;]</value>
      <webElementGuid>79ac5295-7300-4a1f-8b42-22586c9aab02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[3]/following::h2[1]</value>
      <webElementGuid>20bebd87-bff0-47a6-a334-ac7a415f2ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::h2[1]</value>
      <webElementGuid>a3642360-6775-4c9e-a095-c36efbd1681c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Become a member of TechZone']/parent::*</value>
      <webElementGuid>e4199e55-c3a2-48f3-bac9-4abbac951ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f8b4eda6-fcda-4f57-b67a-bb277371fd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Become a member of TechZone' or . = 'Become a member of TechZone')]</value>
      <webElementGuid>446f095d-9145-4674-aa74-a235481f8b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
