<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Joining date_changepasswordprofile</name>
   <tag></tag>
   <elementGuidId>ca70aca2-2bee-420c-9520-6791bb96146e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkChangpasswordprofile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkChangpasswordprofile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab1251d4-11a8-4e3c-ae9c-9dcc8271304d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ca2e99b1-7d06-430f-8f40-58ad9955490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkChangpasswordprofile</value>
      <webElementGuid>1a7e360f-2d75-4329-90dc-6b14d5aafd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changepasswordprofile</value>
      <webElementGuid>4eb6fbed-34ba-4c22-b6bf-b726fa88fdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkChangpasswordprofile&quot;)</value>
      <webElementGuid>c09bda53-e33a-4c03-8319-cf4f5aba040a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkChangpasswordprofile']</value>
      <webElementGuid>cccbb97c-b0d2-42e6-9008-7e52a6c6558a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>1f31a375-f25a-44b3-b0bf-e30e42ff3e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkChangpasswordprofile' and @name = 'changepasswordprofile']</value>
      <webElementGuid>61352b57-73bb-4eb5-a3d3-ab868b56fd98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
