<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ngay</name>
   <tag></tag>
   <elementGuidId>aa69501f-991c-4ced-94c8-f3a2e3563182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MM/YY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7168750e-bf7b-4f78-b550-79ea8a3e8e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardDate</value>
      <webElementGuid>c3b242d0-599b-4f63-b89f-794dbae67dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardDate</value>
      <webElementGuid>e8fc527e-4325-450f-9640-2a296d00f677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-label-change input-has-clear cleave-mm-yy</value>
      <webElementGuid>c5635960-184d-4359-b4df-bbee38706067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>972663d7-4da1-45ab-b28c-799abf837661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(01|02|03|04|05|06|07|08|09|10|11|12)\/[0-9]{2,2}$</value>
      <webElementGuid>1bfac702-580a-4913-8fb5-09fec6ef40f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ac4adac3-6431-4cbb-a12e-cd4838fd4aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>a7da90b3-6808-411b-94dc-ee5f90f625de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9a6cb6a9-7d5a-4b9f-b3f9-f6d4d8095048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Quý khách vui lòng nhập Ngày phát hành</value>
      <webElementGuid>b7f1f179-fe3c-4c15-9f6f-b724dfe66114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-pattern-message</name>
      <type>Main</type>
      <value>Tháng/năm không hợp lệ, vui lòng kiểm tra lại!</value>
      <webElementGuid>526950df-2f97-4abc-8b60-5821536e37e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ba4ea6df-7536-46b8-aae5-5b873152ff8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardDate&quot;)</value>
      <webElementGuid>7ad0dd00-33ce-4869-8928-6eb5b3456439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardDate']</value>
      <webElementGuid>d1a5b5cb-9882-4251-a03f-c5db76579747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardVerify']/div/div[2]/div/div/div[3]/div/div/label/input</value>
      <webElementGuid>cc854649-2cba-4351-9a5d-655f7117d502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/input</value>
      <webElementGuid>a7214c57-261d-4fcf-8603-b077c8992f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardDate' and @id = 'cardDate' and @placeholder = 'MM/YY']</value>
      <webElementGuid>67768282-001e-45e3-915d-1dba5693101e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
