<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Th ni a_card_number_mask</name>
   <tag></tag>
   <elementGuidId>d9eb631c-6c57-4371-a77b-c06753621037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number_mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number_mask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Số thẻ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0949f63d-b564-4c0a-bc37-7fbfa339a1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>digits</value>
      <webElementGuid>54022a31-6b1b-4fcf-b469-f62f43c9e2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-label-change input-has-clear</value>
      <webElementGuid>ed821954-4482-424e-b765-0476aad9000a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập số thẻ
</value>
      <webElementGuid>b0f144c0-05b0-4285-acc3-4ae120e23bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>b02ff490-c05b-43dc-a598-b153aad10e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>da6fc7be-4bd5-4db6-890a-9a3789836c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number_mask</value>
      <webElementGuid>7c45d040-c0f5-4693-8c97-815a8bcdab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number_mask</value>
      <webElementGuid>24b7e29b-00cd-415d-b3b4-beb5c15a60dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>159a6d41-c0d2-4516-9e6b-f35ad925f6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a4a56395-0d51-41c2-a78a-3f4f324d4215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7d8b1f03-8048-4593-917a-2cff4555df78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-bincode</name>
      <type>Main</type>
      <value>970419</value>
      <webElementGuid>d5e401da-86df-44de-8abc-e56e2854ae00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Quý khách vui lòng nhập Số thẻ</value>
      <webElementGuid>fec324e8-0840-457a-96fd-1c379790e4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-length-message</name>
      <type>Main</type>
      <value>Số thẻ không hợp lệ</value>
      <webElementGuid>f8dfad7c-9531-4ec8-865a-018cbfc192b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-bincode-message</name>
      <type>Main</type>
      <value>Thông tin số thẻ chưa hợp lệ, quý khách vui lòng kiểm tra lại</value>
      <webElementGuid>83afdb9f-64bf-4da1-9b17-8e373e2ef634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>#err-card</value>
      <webElementGuid>ed7746d0-8016-4816-ade6-8b90b5561bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number_mask&quot;)</value>
      <webElementGuid>67d87c0c-26ef-4bac-9828-f388a9c1250d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number_mask']</value>
      <webElementGuid>82998261-3509-4d85-a78b-96b026f2c236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardVerify']/div/div[2]/div/div/div/div/div/label/input</value>
      <webElementGuid>b26f1e4f-8c13-4345-b804-1caa6f3584c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4edcc57-7aaf-418b-aecd-3a070cfd372b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'digits' and @placeholder = 'Nhập số thẻ
' and @id = 'card_number_mask' and @name = 'card_number_mask']</value>
      <webElementGuid>367b8192-c397-4747-8a97-2d97a9d8c781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
