<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Categories</name>
   <tag></tag>
   <elementGuidId>6542ae3e-a964-4ea3-ab27-4a874a12141e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pcoded-mtext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Categories&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>203b40cf-c8e6-448f-af84-60a141c1176b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pcoded-mtext</value>
      <webElementGuid>1e6a320a-84f5-454c-872d-8b7cb252f390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>56d7fb58-4a6f-40bf-90b1-9456a4fbdc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/div[@class=&quot;pcoded-main-container&quot;]/div[@class=&quot;pcoded-wrapper&quot;]/nav[@class=&quot;pcoded-navbar&quot;]/div[@class=&quot;nav-list&quot;]/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;pcoded-inner-navbar main-menu&quot;]/ul[@class=&quot;pcoded-item pcoded-left-item&quot;]/li[@class=&quot;pcoded&quot;]/a[@class=&quot;waves-effect waves-dark&quot;]/span[@class=&quot;pcoded-mtext&quot;]</value>
      <webElementGuid>03ee3810-f086-4114-ad3e-965fb406d850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li/a/span[2]</value>
      <webElementGuid>1c68459a-ce7a-4f86-875b-ac4a01699024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnamese'])[1]/following::span[2]</value>
      <webElementGuid>d1121bb6-c062-4d24-9afc-365b39b67cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::span[2]</value>
      <webElementGuid>a10703a9-a04f-4a5f-9dd6-24adb291faa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcategories'])[1]/preceding::span[2]</value>
      <webElementGuid>a3961fa4-cd7e-4c3f-a5fb-18c1e8f7daa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/preceding::span[4]</value>
      <webElementGuid>9d06bccf-c01a-449c-a259-be9d6182631a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Categories']/parent::*</value>
      <webElementGuid>4a993e19-c59f-44f4-ac35-7cb29f4ef3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>076208ad-5746-4582-8964-2a91b81eed91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Categories' or . = 'Categories')]</value>
      <webElementGuid>c02ecb23-c47b-4bdb-a22d-ab2b5305ddda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
