<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Products</name>
   <tag></tag>
   <elementGuidId>c11ac5d0-c9f6-4f52-b566-f6baf6517cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li[4]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Products&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb9df0a7-f6f9-4464-a3f1-09ff8a8f005d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pcoded-mtext</value>
      <webElementGuid>40c322fd-c9ce-45ca-95c7-9633bd6a1a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>f4a4da43-ef4d-457f-a880-536f3d2f59f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/div[@class=&quot;pcoded-main-container&quot;]/div[@class=&quot;pcoded-wrapper&quot;]/nav[@class=&quot;pcoded-navbar&quot;]/div[@class=&quot;nav-list&quot;]/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;pcoded-inner-navbar main-menu&quot;]/ul[@class=&quot;pcoded-item pcoded-left-item&quot;]/li[@class=&quot;pcoded&quot;]/a[@class=&quot;waves-effect waves-dark&quot;]/span[@class=&quot;pcoded-mtext&quot;]</value>
      <webElementGuid>1648c8c6-1c68-46b7-84e1-f3e09fb4df78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li[4]/a/span[2]</value>
      <webElementGuid>3c082b93-cfec-46a5-8759-24c944f7de9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/following::span[2]</value>
      <webElementGuid>de3e9c0a-af8d-4bb4-ab38-e3098e4f7278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcategories'])[1]/following::span[4]</value>
      <webElementGuid>0a574ded-6a91-4ddd-b76d-6ca00268c725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staffs'])[1]/preceding::span[2]</value>
      <webElementGuid>fd5e1a71-bedf-4ea8-9662-6d3863b61535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/preceding::span[4]</value>
      <webElementGuid>d77d539c-8715-4349-bad9-56047134b580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Products']/parent::*</value>
      <webElementGuid>5a874b10-a5d5-48b3-99e8-f3c71e5af37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span[2]</value>
      <webElementGuid>d3231bae-363c-487e-8303-b3d702ff4ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>8c8b5b3f-87d1-49ea-be8e-170971fa2354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
