<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Profile_img-radius</name>
   <tag></tag>
   <elementGuidId>c96e4227-7041-4607-8ff2-89e39331cbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-radius</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/nav/div/div[2]/ul/li/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User-Profile-Image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95be7747-e205-4717-9b45-95c27acadd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>upload/avatar/avatar.jpg</value>
      <webElementGuid>66ad7c75-ea57-400c-b574-3af7e961ef80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-radius</value>
      <webElementGuid>87850c11-66b3-42b0-8d14-b73df79908af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User-Profile-Image</value>
      <webElementGuid>db9abdc5-1f38-4e3f-bebb-02ba8fd63789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/nav[@class=&quot;navbar header-navbar pcoded-header iscollapsed&quot;]/div[@class=&quot;navbar-wrapper&quot;]/div[@class=&quot;navbar-container container-fluid&quot;]/ul[@class=&quot;nav-right&quot;]/li[@class=&quot;user-profile header-notification&quot;]/div[@class=&quot;dropdown-primary dropdown&quot;]/div[@class=&quot;dropdown-toggle&quot;]/img[@class=&quot;img-radius&quot;]</value>
      <webElementGuid>8390884f-c64c-4ba9-908e-e027ddf0980a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/nav/div/div[2]/ul/li/div/div/img</value>
      <webElementGuid>e6fab413-4705-469c-8d2b-8f58abaf51c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User-Profile-Image']</value>
      <webElementGuid>cdd08532-351c-4653-b459-993a21f55f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>354e4c85-e40a-401d-9ea5-3b524589ecb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'upload/avatar/avatar.jpg' and @alt = 'User-Profile-Image']</value>
      <webElementGuid>2a0b7180-a70f-4e12-913a-d81b3e96a1df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
