<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>139633c2-a467-412b-bd5a-3fe0cd2ac2e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.product__item__pic__hover > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>094f0474-69bb-4572-a7c2-b4daa67ca8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/29</value>
      <webElementGuid>b8f969ee-e335-4b65-a783-a09cd295ae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;col-lg-4 col-md-6 col-sm-6&quot;]/div[@class=&quot;product__item&quot;]/div[@class=&quot;product__item__pic set-bg&quot;]/ul[@class=&quot;product__item__pic__hover&quot;]/li[2]/a[1]</value>
      <webElementGuid>1495b52b-7437-4a2c-a8cd-eda0581e989b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/div/div/div/ul/li[2]/a</value>
      <webElementGuid>b8b64318-1991-4b16-98fe-a1f7d6f1718f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z -> A'])[2]/following::a[2]</value>
      <webElementGuid>857e9ddf-afd1-4312-ab36-329b25b3a48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A -> Z'])[2]/following::a[2]</value>
      <webElementGuid>b90cb00c-c9f2-4b82-b76e-a4e94896b2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Asus ROG Strix G15CF (i5-12400F/16GB RAM/512GB SSD/RTX3060TI)'])[1]/preceding::a[1]</value>
      <webElementGuid>542f7516-1c29-4ab5-91a6-79a244e0fa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC MSI Creator P50 (i5-11400/16GB (2X8GB)/512GB SSD/GTX1660S/WL+BT) (11SI-058XVN)'])[1]/preceding::a[4]</value>
      <webElementGuid>1f023986-c12b-4966-855c-30ec9f579aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/29')]</value>
      <webElementGuid>ff91f5a7-9f70-43cb-8fa6-cc714b9ed380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>0630bda1-e8b8-483e-9346-2efe68320efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/29']</value>
      <webElementGuid>e167d77b-77da-4822-a620-10d77f43acf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
