<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__icon_close</name>
   <tag></tag>
   <elementGuidId>46f4a60f-c66d-4a91-8530-4bc4caf75d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon_close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;M&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3071b9d-9756-4075-917f-8eea91989563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_close</value>
      <webElementGuid>94877300-6813-4c89-899b-a934c6055b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;shoping-cart spad&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;shoping__cart__table&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;shoping__cart__item__close&quot;]/a[1]/span[@class=&quot;icon_close&quot;]</value>
      <webElementGuid>11eabf15-18f5-4d3d-83b1-fa5108795e69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/span</value>
      <webElementGuid>8dabe586-1b0d-4302-afe7-ca9a7e3af0d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
