<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Categories</name>
   <tag></tag>
   <elementGuidId>9a55c7a6-1574-4ef9-a9f4-e1f713503659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pcoded-mtext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Categories&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>024420d1-bdf9-4910-8020-f81be2e7c2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pcoded-mtext</value>
      <webElementGuid>b3260986-b989-4d5c-9f15-c7daeb6bf7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>fe805bcf-3e41-4904-8429-99a3c883188b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pcoded&quot;)/div[@class=&quot;pcoded-container navbar-wrapper&quot;]/div[@class=&quot;pcoded-main-container&quot;]/div[@class=&quot;pcoded-wrapper&quot;]/nav[@class=&quot;pcoded-navbar&quot;]/div[@class=&quot;nav-list&quot;]/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;pcoded-inner-navbar main-menu&quot;]/ul[@class=&quot;pcoded-item pcoded-left-item&quot;]/li[@class=&quot;pcoded&quot;]/a[@class=&quot;waves-effect waves-dark&quot;]/span[@class=&quot;pcoded-mtext&quot;]</value>
      <webElementGuid>fbd982f1-01be-4f90-9288-a76485af32e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pcoded']/div[2]/div/div/nav/div/div/div/ul/li/a/span[2]</value>
      <webElementGuid>6dfd6173-b951-421e-9c33-b74794ecfaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnamese'])[1]/following::span[2]</value>
      <webElementGuid>d2bd3e3c-299b-4a94-b964-61fbfb68c1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::span[2]</value>
      <webElementGuid>1656005e-8481-4d77-9dd8-40271315a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcategories'])[1]/preceding::span[2]</value>
      <webElementGuid>53de1fe5-3928-45a5-9e02-9832d52efbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/preceding::span[4]</value>
      <webElementGuid>b851aab1-4ed9-4380-83e8-bd1847e2b83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Categories']/parent::*</value>
      <webElementGuid>1f1b0a18-0ace-4d94-981f-2922b67a65b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>11665dc8-826c-4ef4-811e-11f5e6e49e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Categories' or . = 'Categories')]</value>
      <webElementGuid>822b7da0-70e7-4201-ab45-bfd12b5f2936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
