<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_t hng</name>
   <tag></tag>
   <elementGuidId>0d989444-bc79-4589-a00e-12c5d30d9459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#placeOrderBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='placeOrderBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt hàng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4baaa9fc-9e62-4314-a344-63e32f813d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>83dffc1c-8011-4776-b1ce-8df04371a029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placeOrderBtn</value>
      <webElementGuid>fde960e5-3eb5-4019-a2ed-df67c62e7709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-btn</value>
      <webElementGuid>2630b1d1-1a90-466b-9f54-c46df35ca0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt hàng</value>
      <webElementGuid>4a3ccbfd-ab0b-49b5-84f4-e231a7dc3408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeOrderBtn&quot;)</value>
      <webElementGuid>5c8483fd-a0f1-466f-93b1-eb5770c14d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='placeOrderBtn']</value>
      <webElementGuid>a16c478e-6b32-480b-ac02-1398b19c6dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/div[2]/div/button</value>
      <webElementGuid>cb1bff8d-d5ea-44bb-bacf-3f0739ec3665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MoMo'])[1]/following::button[1]</value>
      <webElementGuid>53602064-b99c-41d4-87ce-3b1e12773632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VNPAY'])[1]/following::button[1]</value>
      <webElementGuid>3ca03439-d0b2-42a4-ba1a-6ce770e88fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ: 12 Chùa Bộc, Đống Đa, Hà Nội'])[1]/preceding::button[1]</value>
      <webElementGuid>ffa837fe-2e80-4295-9dfb-7359780f9ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại: 0934567812'])[1]/preceding::button[1]</value>
      <webElementGuid>1cdc66ea-4676-4196-8f3d-2813f58281e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đặt hàng']/parent::*</value>
      <webElementGuid>c855745c-36c7-44c9-aa97-b93cec0b1ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c683910f-0fe0-4515-a054-ba0b7f32f4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'placeOrderBtn' and (text() = 'Đặt hàng' or . = 'Đặt hàng')]</value>
      <webElementGuid>f8fa0257-0d34-4f7e-a0a7-7f05f811ac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
