<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>91103611-5f96-4f8b-9172-ce0001bcc7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='autofill']/tbody/tr[2]/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(8) > a.btn.btn-danger.delete-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;15 163839 ádfg 374859 nguy@gmail.com 30-11-2024 01:28:35 30-11-2024 01:28:35 On Off Delete&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3feac820-cb86-407a-9696-70ee5bf42e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ab10d6f3-bb61-434b-8cec-358f2ada4f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://techzone.serv00.net/ajax/delete_staff/15</value>
      <webElementGuid>bb105736-48dc-4bc8-b1b7-fbc3c90cb8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger delete-user</value>
      <webElementGuid>83386bfd-aabc-46d7-9c4c-f025f4644b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>7cd3933f-0891-40c6-8c1c-2acb9b53f0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autofill&quot;)/tbody[1]/tr[2]/td[8]/a[@class=&quot;btn btn-danger delete-user&quot;]</value>
      <webElementGuid>d69d1afe-0bc2-460d-9d44-a11d944399dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='autofill']/tbody/tr[2]/td[8]/a</value>
      <webElementGuid>61b32463-7e15-44d4-86d4-cc5fac0222b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[2]</value>
      <webElementGuid>da265b5e-dde9-4bf9-893e-2d3642a19f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Off'])[2]/following::a[1]</value>
      <webElementGuid>9d2dc90d-4beb-4847-8b56-bd0ed92f98cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On'])[2]/following::a[1]</value>
      <webElementGuid>db1a8a20-7e11-4fa1-b4d2-dbe3559fc6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rty qưe'])[1]/preceding::a[1]</value>
      <webElementGuid>7f5f8ae8-b4e2-4abf-b775-93c104ccc61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qưertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm'])[1]/preceding::a[1]</value>
      <webElementGuid>756eb07c-c741-4426-86e2-7d984fffd0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>09616a78-e5dd-40ce-8baf-d232bc468b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/a</value>
      <webElementGuid>d5d89760-df0c-41d8-967b-b3b46226d78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>077f484f-7322-454a-b8c7-4632ccb63936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
