<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place Order</name>
   <tag></tag>
   <elementGuidId>3d1284b2-87c5-4aaf-b5fc-83877f1bd253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#placeOrderBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='placeOrderBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Place Order&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e44b649c-c8e7-4380-8ab7-a1cfa68cb7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1635791a-1baf-471d-8169-69fa918496b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placeOrderBtn</value>
      <webElementGuid>066cb6b8-3ad7-48e9-a576-1c2a4713a754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-btn</value>
      <webElementGuid>42aad693-5107-47b0-b425-b1c1b15fe012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place Order</value>
      <webElementGuid>7969cf31-d0ad-434b-b51c-5f4c6873b45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeOrderBtn&quot;)</value>
      <webElementGuid>4a127f4c-abc0-4a68-96d1-4f812a6b2dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='placeOrderBtn']</value>
      <webElementGuid>641bccc8-a73f-429f-940f-cb4c3c1c469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/div[2]/div/button</value>
      <webElementGuid>2b2c7dea-316d-4a10-8b59-6ed5c3233917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MoMo'])[1]/following::button[1]</value>
      <webElementGuid>133778d7-431c-454e-a480-64bc6adb9d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VNPAY'])[1]/following::button[1]</value>
      <webElementGuid>fe4ceda9-4c86-4e70-9eac-b421cdbc91e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address: 12 Chùa Bộc, Đống Đa, Hà Nội'])[1]/preceding::button[1]</value>
      <webElementGuid>5f5c230c-3842-4d1c-a496-4da87d7d20c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone: 0934567812'])[1]/preceding::button[1]</value>
      <webElementGuid>28694ee3-ab3b-4799-abd3-f7d434323163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place Order']/parent::*</value>
      <webElementGuid>5bc9e900-6880-4226-80b9-3e392fc7f762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c80329d3-0cc8-49df-bab7-58018a2e64b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'placeOrderBtn' and (text() = 'Place Order' or . = 'Place Order')]</value>
      <webElementGuid>906c8dea-d9b9-4b91-8e17-9cb7ac4c9e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
