<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__icon_close</name>
   <tag></tag>
   <elementGuidId>e20178b5-f86a-4a05-926f-565f75c68e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon_close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;M&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8ef255c-b72d-44df-9433-e5d743bfd037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_close</value>
      <webElementGuid>880443fe-f056-4b1b-bcde-b26634de0d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;shoping-cart spad&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;shoping__cart__table&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;shoping__cart__item__close&quot;]/a[1]/span[@class=&quot;icon_close&quot;]</value>
      <webElementGuid>320d50db-507e-4093-b525-be0a9b791d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/span</value>
      <webElementGuid>18cd8eda-f8d3-4ea5-83fd-c6114f700a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
