<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_xo sn phm khi danh sch yu thch</name>
   <tag></tag>
   <elementGuidId>f01361df-4189-436f-afbf-5522be375c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notifDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notifDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đã xoá sản phẩm khỏi danh sách yêu thích&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50112745-046d-4d6d-bb3d-b0127d1af2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notifDiv</value>
      <webElementGuid>ea012caf-6f84-445f-b14b-b0c1f81c8ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đã xoá sản phẩm khỏi danh sách yêu thích</value>
      <webElementGuid>7c48f7b7-c54c-47a6-b8c7-75456a69efbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notifDiv&quot;)</value>
      <webElementGuid>a823fadd-22fc-4d6b-b956-d13a7d73af31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notifDiv']</value>
      <webElementGuid>dc681d76-898f-4819-9cbf-149faabdde05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm'])[3]/following::div[5]</value>
      <webElementGuid>cb80bb19-1ce0-4703-abd7-24e468d7f144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[3]/preceding::div[1]</value>
      <webElementGuid>9bfa68a3-3f7f-4b82-b372-242d64a61607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[3]/preceding::div[2]</value>
      <webElementGuid>31f9c4b1-5402-4d9c-a1b3-d80b10352f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đã xoá sản phẩm khỏi danh sách yêu thích']/parent::*</value>
      <webElementGuid>b737558f-925f-4326-8bf2-0a62c723454d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>8c09e85e-9bdd-476d-9173-d7e6a654dbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notifDiv' and (text() = 'Đã xoá sản phẩm khỏi danh sách yêu thích' or . = 'Đã xoá sản phẩm khỏi danh sách yêu thích')]</value>
      <webElementGuid>141da164-7ad0-4ee3-9da2-b01a0ccceaf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
