<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lenovo</name>
   <tag></tag>
   <elementGuidId>c9e088b7-48a8-4b7a-bbd4-b0d0e6ea54e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.item-show_item-content > a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Lenovo')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lenovo&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e85f1fa3-65d7-42ba-b3ce-414e957fa22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/subcategories/2</value>
      <webElementGuid>b2c948f5-eda0-41d4-a3b7-cae0ff08e058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lenovo</value>
      <webElementGuid>54415b5e-5dc8-4749-94d4-8e3dcc92aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;hero&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3&quot;]/div[@class=&quot;hero__categories&quot;]/ul[@class=&quot;submenu-list&quot;]/div[@class=&quot;item-show active&quot;]/div[@class=&quot;item-show_item&quot;]/p[@class=&quot;item-show_item-content&quot;]/a[2]</value>
      <webElementGuid>973ad550-ff9d-486e-922e-0ea4f0b235aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lenovo')])[3]</value>
      <webElementGuid>138eabd4-f6db-43ad-83dd-0e1a940a028a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple (MacBook)'])[3]/following::a[1]</value>
      <webElementGuid>16f8c3f1-c115-4844-8a40-1b2225394efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[3]/following::a[2]</value>
      <webElementGuid>e3b3b2b2-913c-4f20-8225-c3a1598b6bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dell'])[3]/preceding::a[1]</value>
      <webElementGuid>bbf899dd-0d6d-45d5-99f0-642ad93c25ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surface'])[3]/preceding::a[2]</value>
      <webElementGuid>22f162fe-5d29-4370-870c-5ab21a53f529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/subcategories/2')])[23]</value>
      <webElementGuid>3079c5d5-4ca9-49c5-894d-39f015fef2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a[2]</value>
      <webElementGuid>e5e3c78f-c7f4-42d3-b8e8-d83fe1661e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/subcategories/2' and (text() = 'Lenovo' or . = 'Lenovo')]</value>
      <webElementGuid>af72d5ac-6a43-41ec-848f-6a1eff1ce16e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
