<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-</name>
   <tag></tag>
   <elementGuidId>40f89005-9345-4aab-8261-142dd64dde75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dec.qtybtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenovo ThinkPad L14 Gen 4 (21H1003AVA) (i7-1360P/16GB RAM/512GB SSD)'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;-&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6504fc0e-7093-491a-a507-108fe48fb099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dec qtybtn</value>
      <webElementGuid>f95c348e-4047-4812-bd0b-1e98630bd657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>adead7c8-c0a0-40e6-9024-e2357eae7398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;shoping-cart spad&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;shoping__cart__table&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;shoping__cart__quantity&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;pro-qty&quot;]/span[@class=&quot;dec qtybtn&quot;]</value>
      <webElementGuid>ef215654-795d-4324-a272-74dc6e232300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenovo ThinkPad L14 Gen 4 (21H1003AVA) (i7-1360P/16GB RAM/512GB SSD)'])[1]/following::span[1]</value>
      <webElementGuid>af1cdf8e-2a72-48cb-83cb-b4f8d058ac2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::span[1]</value>
      <webElementGuid>b213178c-bdc2-4fba-9649-e311be7e2047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::span[1]</value>
      <webElementGuid>ec7b0a89-4dea-4030-a54b-84a5d67d89f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon Codes'])[1]/preceding::span[3]</value>
      <webElementGuid>e5bd3ba7-972f-489d-910f-6d1361e898fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>bc79d92d-47b2-488a-8204-6eeed1e51626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/span</value>
      <webElementGuid>7147e818-6385-4f78-ac3c-dc1db2900062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '-' or . = '-')]</value>
      <webElementGuid>a3ad9866-d2e7-4734-b8fb-7721cd3835d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
