<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Laptop</name>
   <tag></tag>
   <elementGuidId>d8e28671-51a3-4e9a-80af-4169b5d7a48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sidebar__item > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Laptop')])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Laptop&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1cfcc65a-de83-4ee3-9066-da866dbd248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/1</value>
      <webElementGuid>1a95bc4e-ac1f-4328-bf6c-505ed507de1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laptop</value>
      <webElementGuid>4eb1bb2e-07c6-421a-8db2-69f04013ba84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;product spad&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-5&quot;]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebar__item&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>e70ec018-e00c-4264-8e0b-0aad058c34c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Laptop')])[4]</value>
      <webElementGuid>069d68dc-796e-464d-b996-ff94350c3fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[1]/following::a[1]</value>
      <webElementGuid>5e4ac3a6-8982-4f7a-b67b-3b0018e6b3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='> All Bàn phím - Chuột'])[1]/following::a[1]</value>
      <webElementGuid>76738648-a42b-41a9-9f7f-1c2db55f2c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC'])[4]/preceding::a[1]</value>
      <webElementGuid>bf3470be-ca60-4ee9-8878-e6e1ab25eb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Console'])[4]/preceding::a[2]</value>
      <webElementGuid>17c0e546-40b3-43b3-869f-edd9488f3e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/categories/1')])[7]</value>
      <webElementGuid>81fdfcdc-cb27-4d61-a008-ac1a20e2a71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>7ddc3969-2817-4d1c-8e8b-75e3ff99394a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories/1' and (text() = 'Laptop' or . = 'Laptop')]</value>
      <webElementGuid>7e135a62-94e9-4ea3-b5c8-ecc2a8fb7fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
